import React from 'react';

const TestComp = () => {
    return (
        <>
            <div id='form-div' style={{ "backgroundColor": "rgb(138, 75, 40)", "width": "363px", "height": "389px", "borderRadius": "11px" }}> <form id='form' style={{ "width": "auto", "display": "flex", "flexDirection": "column", "alignItems": "center", "height": "389px", "padding": "0px" }}> <h1 id='form-header' style={{ "top": "10px", "color": "rgb(59, 165, 119)" }} key='0'> Sign Up Below </h1> <div draggable='true' id='elementId' key='1'> <input type='text' id='input-text' placeholder='First Name' style={{ "marginTop": "20px", "border": "1px solid rgb(0, 0, 0)", "width": "194px", "boxShadow": "rgb(39, 86, 1) 4px 4px 4px", "borderRadius": "40px", "backgroundColor": "rgb(166, 202, 129)" }} /> </div> <div draggable='true' id='elementId' key='2'> <input type='text' id='input-text' placeholder='Last Name' style={{ "marginTop": "20px", "border": "1px solid rgb(0, 0, 0)", "width": "194px", "boxShadow": "rgb(39, 86, 1) 4px 4px 4px", "borderRadius": "2px", "backgroundColor": "rgb(166, 202, 129)" }} /> </div> <div draggable='true' id='elementId' key='3'> <input type='text' id='input-text' placeholder='Last Name' style={{ "marginTop": "20px", "border": "1px solid rgb(0, 0, 0)", "width": "194px", "boxShadow": "rgb(39, 86, 1) 4px 4px 4px", "borderRadius": "2px", "backgroundColor": "rgb(166, 202, 129)" }} /> </div> <div draggable='true' id='elementId' key='4'> <input type='text' id='input-text' placeholder='' style={{ "marginTop": "20px", "border": "1px solid rgb(0, 0, 0)", "width": "194px", "boxShadow": "rgb(39, 86, 1) 4px 4px 4px", "borderRadius": "2px", "backgroundColor": "rgb(166, 202, 129)" }} /> </div> <div draggable='true' id='elementId' key='5'> <input type='text' id='input-text' placeholder='' style={{ "marginTop": "20px", "border": "1px solid rgb(0, 0, 0)", "width": "194px", "boxShadow": "rgb(39, 86, 1) 4px 4px 4px", "borderRadius": "2px", "backgroundColor": "rgb(166, 202, 129)" }} /> </div> <div draggable='true' id='elementId' key='6'> <input type='text' placeholder='Password' style={{ "WebkitTextSecurity": "disc", "marginTop": "20px", "borderRadius": "2px", "backgroundColor": "rgb(166, 202, 129)", "border": "1px solid rgb(0, 0, 0)", "width": "194px", "boxShadow": "rgb(39, 86, 1) 4px 4px 4px" }} /> </div> <button type='submit' id='submit' draggable='true' style={{ "marginTop": "10px" }} key='7'> Login </button> </form> </div>
        </>
    )

}

export default TestComp;
