"""empty message

Revision ID: 89ab4ed9fffe
Revises: dc35f780bfe0
Create Date: 2021-05-10 17:59:39.119025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ab4ed9fffe'
down_revision = 'dc35f780bfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Form_userId_key', 'Form', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Form_userId_key', 'Form', ['userId'])
    # ### end Alembic commands ###
